### ISSUE TITLE
Check working from shell but not in nagios

### ISSUE THREAD

**Issue by domgre** [BaldMansMojo/check_vmware_esx#76] opened 2015-10-16 11:23 UTC
Hi,
i've newly installed  Centreon an the check_vmware_esx-plugin.
For testing the script i connected via putty an logged on as user nagios via "su nagios"

when running the script everything is ok:
![console](https://cloud.githubusercontent.com/assets/15156821/10540472/a6e2ebd6-7408-11e5-98df-152822308f02.JPG)

But when running the script from nagios i always get a critical status and no output:

![nagios](https://cloud.githubusercontent.com/assets/15156821/10540503/e14cf582-7408-11e5-9397-e8a53d59d52c.JPG)

Can anyone help me?

**Comment by BaldMansMojo** [comment] 2015-10-16 11:43
2 different things. From the commandline you start perl an tell perl to interpret the plugin. From Nagios you let the plugin do the work. Normally there is no need to call the command interpreter explicity.

Every script in Unix/Linux should contain a first line start with #! which tells the syste that the next is the interpreter to use.
For example:
#!/bin/bash
So for a perl script it should be
#!/usr/bin/perl
in most cases. So for a test  go to the directory where you installed and call it from the shell with ./check_vmware_esx.pl.....
If this doesn't work check the path of your perl interpreter (which perl) and adopt the first line of the script.
If this does't work it can be that the problem is within centreon. I don't know Centreon but within Nagios 3.x we habe the embedded perl interpreter which will interpret each perl programm instead of the system one. This little piece of scrap was initially designed to speed up perl plugins. but it is very limited. Hardware is much more faster today and there is no need to use it. I always recommend to disable it completely. (nagios.cfg)
Regards
Martin

**Comment by domgre** [comment] 2015-10-16 15:41
Thanks for your tipps, the script runs properly when callin via ./check:vmware:esx.pl....

I couldn't find an integraded perl interpreter in centreon so far, i will take a deeper look tomorrow.

**Comment by BaldMansMojo** [comment] 2015-10-16 21:22
I read some docs because I don't Centreon. It's a little bit exotic these days. I would prefer Naemon. See https://documentation.centreon.com/docs/centreon/en/2.6.x/user/configuration/04commands.html#definition
According to this you add a Perl program with the Perl connector.https://documentation.centreon.com/docs/centreon-perl-connector/en/latest/

Well - and if you look into the release notes https://documentation.centreon.com/docs/centreon-perl-connector/en/latest/release_notes/centreon_connector_perl_1_0_0.html what did you see? Our old shitty little friend the embedded Perl connector.Reading the technical part shows that not your systems Perl is executing the code. It's the embedded interpreter. So don't choose it.

So because it's definetely a Centreon issue I will close this one.

Regards
Martin

**Closed by BaldMansMojo** 2015-10-16 21:22 UTC

**Comment by domgre** [comment] 2015-10-17 07:54
I got it running!

After hours of searching for different issues it was a very simple one. With the use of nagios_capture.pl from http://www.waggy.at/nagios/capture_plugin.htm i captured the output from the check_vmware_esx.pl in nagios an found out that it could not find the module help.pm in @inc. The directory modules was in @inc, i added the full path to the script and then it was running!

Thanks for your help.

**Comment by BaldMansMojo** [comment] 2015-10-17 12:19
Wel - this was documented in the Readme:

Second install the plugin
-------------------------
.......
-> Adjust the path for the modules directory (use lib "modules") to fit your system (for example: use lib "/usr/local/libexec/myplugins/modules")

That's why I always say: readme means do it (reading) and do it carefully.
Regards
Martin
