### ISSUE TITLE
Undefined subroutine &Vim::unset_logout_on_disconnect called at ./check_vmware_esx line 8035.

### ISSUE THREAD

**Issue by CoinKoin** [BaldMansMojo/check_vmware_esx#54] opened 2015-04-28 16:03 UTC
Maybe you can help me ...
[nagios@nagios plugins]$ ./check_vmware_esx -f /home/nagios/authfile -D 10.0.0.1 -S runtime -s listvms
Undefined subroutine &Vim::unset_logout_on_disconnect called at ./check_vmware_esx line 8035.
[nagios@nagios plugins]$ ./check_vmware_esx -f /home/nagios/authfile -D 10.0.0.1 --select=soap
Undefined subroutine &Vim::unset_logout_on_disconnect called at ./check_vmware_esx line 8035.

When i do something, like that :
./check_vmware_esx -f /home/nagios/authfile -D 10.0.0.1 -N VMNAME -S cpu -s usage
VMware machine VMNAME does not exist
./check_vmware_esx -f /home/nagios/authfile -D 10.0.0.1 -S runtime
There are no VMs.

I have install "VMware-vSphere-Perl-SDK-5.5.0-2043780.x86_64.tar.gz"
My vCenter is "5.5.0 U2b R2183111"
I use "compiled version" with MakeFile and ".pl" version with export "modules/", same result.

If i use "check_vmware_api.pl" it's work ... But logs in BDD is amazing (~700 checks/5 minutes)

Any idea ?
Thx for your job :)

**Comment by BaldMansMojo** [comment] 2015-04-28 17:17
First it has nothing to do with "compiled version" or not. The Makefile only takes care for aasembling all in one file. It was the wish of some people because thy preferred a single file. I prefer a modules subdirectory because using the speeds up the execution a little bit. Instead of loading a huge file each time it is called only the components needed are loaded.

Using check_vmware_api.pl works because no session_file is used. This never worked in this plugin. Defect by design. So every time you call the plugin you have a new login instead of reusing an existing session.

Because Unix/Linux systems don't use "extensions" like M$ don't care about the name. If it is executable and the Perl interpreter has the right path (first line of the program) it should work.

I had this error in the past but it was fixed in February 2014. It can be a subsequent error.

First try to login with user and password instead of using the authfile. Be sure the rights on the directory were to store the session file is ok. Default is (around line 1284):

my $plugin_cache="/var/nagios_plugin_cache/";  

Directory for caching plugin data. Good idea to use a tmpfs because it speeds up operation.

Modify the line to your needs. If it doesn't exist (or the rights are wrong) this error is displayed from the VMware perl SDK because the subroutine can't be called.

Give me a feedback (even if itworks). And have a look at the closed issues. We had this problem several times.

Martin

**Comment by CoinKoin** [comment] 2015-04-28 19:22
Thank you for your quick response, I appreciate that.

Firstly you are right, it is not compiled, but a concatenation into a single file. Poor choice of vocabulary, sorry. I saw the "shebang" unix possible to run the file with a "./" so no extension.
You are right again, the script "check_vmware_api.pl" even using the "-S sessionfile" does not work. I have seen it with a SQL query in the VIM_VCDB database.

I tried to connect using the torque "user/password" and I can confirm that these working properly. I get the same error with "-u & -p".
I also checked the permission to the "/home/nagios" containing session files, it's good. The session files are generated with the same torque user/group than running your script.
The variable "my $ plugin_cache" pointing to directory /home/nagios.

**Comment by CoinKoin** [comment] 2015-05-05 10:59
I'm back with great NEWS !!
Finaly i found how to solve this problem.
After few tests, in many differents environnement, i receive 1 error in "perl module".
The malicious module "Net-HTTP" in version 6.07 is guilty !
Why this one ? I don't know and i can't explain ... But i fix this with install "Net-HTTP-6.08002" version.
Thank you so much for this plugins, my vCenter is alive now :)
I hope my issue can help someone, you can close this one.

*I'm happy, it's working*
CoinKoin.

**Closed** 2015-05-31 00:00 UTC
