### ISSUE TITLE
Issue with session files

### ISSUE THREAD

**Issue by debelan** [BaldMansMojo/check_vmware_esx#67] opened 2015-06-10 16:51 UTC
Hello,

I have the following issue, the script is working everything is fine but till first execution ... I'm using tmpfs ( i've tried with another folder with 775 permissions) to store session files: $sessionfile_dir_def="/mnt/check_tmp/"

When I run the script for first time it creates session file and it gives me  desired output, but when I run it again it just time out, when I delete the session file from the directory, script is working.

I'm not sure is this related but I'm using port forwarding and the url is 127.0.0.1:8080 
I've also tryed with --sslport=8080, same result

**Comment by BaldMansMojo** [comment] 2015-06-10 17:41
I've never see this. Normally something like this happens only with wrong access rights.. First test it form the command_line (as root). If this works test it as your Nagios user. If this won't work you have a problem with access rights. If it won't work with root you may habe a problem with you network configuration. I never did such things with monitoring.

The sessionfile should have a name like 192.168.10.53_session.

The content should look like

#LWP-Cookies-1.0
Set-Cookie3: vmware_soap_session="\"52a9b7e3-0ff5-9c5f-6269-4884734e27fd\""; path="/"
; domain=192.168.10.53; path_spec; secure; discard; HttpOnly; version=0

Regards
Martin

**Comment by debelan** [comment] 2015-06-11 08:19
Hi Martin,

So, I've tried with nagios user as well  - this is my session folder - 
"ls -ld check_tmp/
drwxrwxrwt 2 root root 80 Jun 10 18:45 check_tmp/"

I've try first to start it with nagios user when I try to execute the script again even with root result is the same, just timeout when I delete session file script is working

**Comment by BaldMansMojo** [comment] 2015-06-11 08:39
Which Perl SDK is installed? Which version do your Vshere systems have?

**Comment by debelan** [comment] 2015-06-11 08:42
It's a  VMware-vSphere-Perl-SDK-5.1.0-780721.x86_64

**Comment by debelan** [comment] 2015-06-11 08:44
The more interesting thing is that this happens only with my external server, I have 6 hosts in my internal network and it's working for them. I think that it got confused somehow with this different ssl port.

**Comment by BaldMansMojo** [comment] 2015-06-11 08:50
External - that's it. You hadn't mention it. With an external server youhave something in between. Firewall, router, something with NAT, balancer - whatever.  I'm quite sure that it's a network problem. Okay - according to our networks administrators the network will never be a problem. That's a dogma. But I'M no network admin and so I say it's the problem. I think the sessionfile won't fit. So here you have to debug. If you can't solve the problem go back to authentication without session file (--nosession). The old op5 plugin never used session files.

**Comment by debelan** [comment] 2015-06-11 08:58
It's ALIVE! Thank you, it's working without session file now and it's working fine, but still why this session file doesn't fit the second time ? There is a router in between but the port is pointing to the right place and it is working but just one time with session file ..

Thank you for your help

**Comment by BaldMansMojo** [comment] 2015-06-11 09:06
First check it uses the useri/password and generates the sessionfile. Second check it looks for an exsting session (sessionfile) and reuses it. You can play around with the command line tools from the SDK. Maybe that you can reproduce the error. To me it looks like an expired or cut session. therefore you have a session file not valid.

**Comment by debelan** [comment] 2015-06-11 09:14
I will try to reproduce it. I want to ask you something else, is it possible to check for snapshots with this script, I did not found any options for snapshots

**Comment by BaldMansMojo** [comment] 2015-06-11 10:10
No. But there is a good script from Consol to do it.http://labs.consol.de/lang/en/nagios/check_vmware_snapshots/

**Comment by debelan** [comment] 2015-06-11 11:38
Thank you, again, great stuff.

**Comment by BaldMansMojo** [comment] 2015-06-16 11:43
I will close this issue for now. If there is something new please reopen it.

**Closed by BaldMansMojo** 2015-06-16 11:43 UTC
