### ISSUE TITLE
plugins error

### ISSUE THREAD

**Issue by erpiu72** [BaldMansMojo/check_vmware_esx#201] opened 2022-09-30 15:44 UTC
Good morning

I installed the plugins on a centos 8 with sdk 6.5 and all its components, I verified that all the perl components were present and despite this it continues to give me this error.

Use of uninitialized value in lc at /usr/lib64/perl5/libwww-perl-5.837/lib/HTTP/Cookies.pm line 573.
Server version unavailable at 'https://localhost:443/sdk/vimService.wsdl' at /usr/share/perl5/VMware/VICommon.pm line 734.

**Comment by erpiu72** [comment] 2022-10-08 08:22
searching on the internet i found some articles now i came to this message

/usr/bin/perl: symbol lookup error: /usr/lib64/perl5/auto/MIME/Base64/Base64.so: undefined symbol: Perl_Istack_sp_ptr

**Comment by BaldMansMojo** [comment] 2022-10-08 12:00
Hi,
errors like this are normally not caused by plugin. It's caused by libwww-perl. Or the SDK itself. According to your message it's caused by your VMWare installation. The server version is not delivered by your ESX host to the SDK. So first try with command line tools.

See:
[https://www.google.de/search?q=vmware+perl+sdk+server+version+unavailable&source=hp&ei=FWZBY_iLGrmSxc8Pk-OEmA4&iflsig=AJiK0e8AAAAAY0F0JaJ9YU0TdXKpVKZaeFT2m7O7idaS&ved=0ahUKEwi46rG_ytD6AhU5SfEDHZMxAeMQ4dUDCAg&uact=5&oq=vmware+perl+sdk+server+version+unavailable&gs_lcp=Cgdnd3Mtd2l6EAMyBggAEB4QFlDyBljyBmCiCmgBcAB4AIABaIgBaJIBAzAuMZgBAKABAqABAbABAA&sclient=gws-wiz](url)

and

[https://community.spiceworks.com/topic/458264-nagios-check_vmware_api-pl-server-version-unavailable](url)

This is not a plugin error. Therefore I close this issue.

**Closed as completed by BaldMansMojo** 2022-10-08 12:00 UTC
