### ISSUE TITLE
Error  on Esx metrics

### ISSUE THREAD

**Issue by talbaror** [BaldMansMojo/check_vmware_esx#89] opened 2016-04-12 20:07 UTC
Hello ,
Suddenly i got error on all my monitoring metrics , using Icinga2 2.4.4 as follows below
Any idea how to solve it ?
Please advice 
Thanks
`Can't kill a non-numeric process ID at /usr/lib/nagios/plugins/check_vmware_esx.pl line 1744.`

**Comment by BaldMansMojo** [comment] 2016-04-12 22:26
This comes from 
 # Third - check for the process which wrote the lock file the last time
$PID_exists = kill 0, $PID_old;

So the code befor extracts the PID from the session lock file. The file looks like

$> more 10.102.9.48_session_locked
9452
So it should contain only the PID from the process currenttly using the session. If there is any other value I don't know from where it comes. Same if the file is empty.
Solving (from my kind of view) is easy Stop Icinga and remove all session files and session lockfiles. Start Icinga.

If the session files and session lock files are scrap this is normally caused by insufficient rights (user, groups, access). Check it if that will happen again.

Give me a note if it works again so I can close this issue.
Regards - Martin

**Comment by talbaror** [comment] 2016-04-22 08:26
Hello,
Sorry for the late response , i was away for while, any way what is exactly "remove all session files"
is it related to "/run/icinga2/cmd" ?
Thanks

**Comment by BaldMansMojo** [comment] 2016-04-22 09:18
Th plugin stores the sessions in a session file. The SDK uses the web interface and the communication ist done by http/https. So first it looks for a valid session. (like a web browser). I there is no session it will login and store the session information in a session file. In Vshpere cCenter you will see it as open session. This avoid a permanent login/logout for every check. an open session will be used. 

Defaul (line 1332) is:

my $sessionfile_dir_def="/tmp/"; 

Filename is for example 192.168.10.3_session and the lock file (to lock the session if it's in use) is for example 192.168.10.3_session_locked.

So stop Icinga, remove the files and start again.

**Comment by talbaror** [comment] 2016-04-22 12:15
just checked, no such file type , i have only "/tmp/FileCache_icingaweb"
thanks

**Comment by BaldMansMojo** [comment] 2016-04-22 14:12
This is the default. I don't know how you have configured the plugin. Please check your configuration. I have checked our conversation. Am I right that it worked in the past and had stop working now? If you don't have any session files It means that the plugin can't write ones. Please check where the files should be stored (default in plugin or overwritten by command line). May be you have changed the rights of a directory.

For testing there is a switch --nosession. Use it. But don't use for production. It will cause a lot of longin/logout messages. 

I think you have a problem with the directory for the session files.

**Comment by geotekberlin** [comment] 2018-04-05 10:35
After Upgrading Icinga from 2.8.1 to 2.8.2 (running on OpenSuse 42.3 which has not changed) we also start getting these errors sporadically on some VMware servers. When this happens, we can see stale empty (!) files of the type **servername_session_locked**. After manually deleting these files monitoring resumes.
Upgrading to the latest **VMware SDK Vmware-vSphere-Perl-SDK-6.5.0-7397310.x86_64** seems to have improve the situation somewhat but not satisfactorily. We will try to automatically remove those stale lock files via CRON script, but this can only be a workaround.

**Comment by BaldMansMojo** [comment] 2019-05-26 02:28
Try latest version. It contains a lot of pull request and one was an improved session handling from Sven Nierlein.

Regards
Martin

**Closed by BaldMansMojo** 2019-05-26 02:28 UTC
